version: "3.8"
services:
  proxy:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
      - db
  app:
    build: app
    volumes:
      - app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
  app:
